language: python
dist: xenial
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.10-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip wheel
  - pip install -U -r requirements.test.txt
  - pip install .[oidc]

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_pyramid
  - psql -c 'create database travis_ci_test;' -U postgres
  - pytest --cov-report= --cov=anyblok_pyramid anyblok_pyramid/tests
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-bloks auth
  - pytest --cov-report= --cov=anyblok_pyramid anyblok_pyramid/bloks/auth
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-bloks auth-password
  - pytest --cov-report= --cov=anyblok_pyramid anyblok_pyramid/bloks/password
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-bloks authorization
  - pytest --cov-report= --cov=anyblok_pyramid anyblok_pyramid/bloks/authorization
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-bloks user-identity
  - pytest --cov-report= --cov=anyblok_pyramid anyblok_pyramid/bloks/user_identity

after_success: coveralls --data_file=.coverage --config_file=.coveragerc
