language: python
dist: xenial
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U psycopg2
  - pip install -U anyblok
  - pip install -U flake8
  - pip install -U pytest-cov
  - pip install -U pytest
  - pip install -U WebTest
  - pip install -U coveralls
  - pip install .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_pyramid --ignore F999
  - psql -c 'create database travis_ci_test;' -U postgres
  - pytest --cov-report= --cov=anyblok_pyramid anyblok_pyramid/tests
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - pytest --cov-report= --cov=anyblok_pyramid anyblok_pyramid/bloks
  
after_success:
  coveralls --data_file=.coverage --config_file=.coveragerc
